services:
  server:
    build: ./server
    network_mode: "host"
    environment:
      - HOST_ADDRESS=127.0.0.1
    ports:
      - "5000:5000"
    volumes:
      - ./database/schema.sql:/app/schema.sql

  client-python:
    build: ./client-python
    stdin_open: true
    tty: true
    network_mode: "host"
    environment:
      - SERVER_HOST=127.0.0.1
      - SERVER_PORT=5000
    depends_on:
      - server
    volumes:
      - ./database/schema.sql:/app/schema.sql

  client-node:
    build: ./client-node
    stdin_open: true
    tty: true
    network_mode: "host"
    environment:
      - SERVER_HOST=127.0.0.1
      - SERVER_PORT=5000
    depends_on:
      - server
    volumes:
      - ./database/schema.sql:/app/schema.sql
